/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

/**
 *
 * @author brend
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemBuscarProductos = new javax.swing.JMenuItem();
        jMenuItemAgregarProductos = new javax.swing.JMenuItem();
        jMenuItemModificarProductos = new javax.swing.JMenuItem();
        jMenuItemEliminarProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemBuscarClientes = new javax.swing.JMenuItem();
        jMenuItemAgregarClientes = new javax.swing.JMenuItem();
        jMenuItemModificarClientes = new javax.swing.JMenuItem();
        jMenuItemEliminarClientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemBuscarMantenimiento = new javax.swing.JMenuItem();
        jMenuItemAgregarMantenimiento = new javax.swing.JMenuItem();
        jMenuItemModificarMantenimiento = new javax.swing.JMenuItem();
        jMenuItemEliminarMantenimiento = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemBuscarFactura = new javax.swing.JMenuItem();
        jMenuItemAgregarFactura = new javax.swing.JMenuItem();
        jMenuItemEliminarFactura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tienda de ciclismo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 340, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagen3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ciclismo-de-ruta-para-principiantes.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 300));

        jMenu1.setText("Registro Productos");

        jMenuItemBuscarProductos.setText("Buscar");
        jMenu1.add(jMenuItemBuscarProductos);

        jMenuItemAgregarProductos.setText("Agregar");
        jMenu1.add(jMenuItemAgregarProductos);

        jMenuItemModificarProductos.setText("Modificar");
        jMenu1.add(jMenuItemModificarProductos);

        jMenuItemEliminarProductos.setText("Eliminar");
        jMenu1.add(jMenuItemEliminarProductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registro del cliente");

        jMenuItemBuscarClientes.setText("Buscar");
        jMenu2.add(jMenuItemBuscarClientes);

        jMenuItemAgregarClientes.setText("Agregar");
        jMenu2.add(jMenuItemAgregarClientes);

        jMenuItemModificarClientes.setText("Modificar");
        jMenu2.add(jMenuItemModificarClientes);

        jMenuItemEliminarClientes.setText("Eliminar");
        jMenu2.add(jMenuItemEliminarClientes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Mantenimiento");

        jMenuItemBuscarMantenimiento.setText("Buscar");
        jMenu3.add(jMenuItemBuscarMantenimiento);

        jMenuItemAgregarMantenimiento.setText("Agregar");
        jMenuItemAgregarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarMantenimientoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAgregarMantenimiento);

        jMenuItemModificarMantenimiento.setText("Modificar");
        jMenu3.add(jMenuItemModificarMantenimiento);

        jMenuItemEliminarMantenimiento.setText("Eliminar");
        jMenu3.add(jMenuItemEliminarMantenimiento);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Facturación");

        jMenuItemBuscarFactura.setText("Buscar");
        jMenu4.add(jMenuItemBuscarFactura);

        jMenuItemAgregarFactura.setText("Agregar");
        jMenu4.add(jMenuItemAgregarFactura);

        jMenuItemEliminarFactura.setText("Eliminar");
        jMenu4.add(jMenuItemEliminarFactura);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAgregarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAgregarMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAgregarClientes;
    private javax.swing.JMenuItem jMenuItemAgregarFactura;
    private javax.swing.JMenuItem jMenuItemAgregarMantenimiento;
    private javax.swing.JMenuItem jMenuItemAgregarProductos;
    private javax.swing.JMenuItem jMenuItemBuscarClientes;
    private javax.swing.JMenuItem jMenuItemBuscarFactura;
    private javax.swing.JMenuItem jMenuItemBuscarMantenimiento;
    private javax.swing.JMenuItem jMenuItemBuscarProductos;
    private javax.swing.JMenuItem jMenuItemEliminarClientes;
    private javax.swing.JMenuItem jMenuItemEliminarFactura;
    private javax.swing.JMenuItem jMenuItemEliminarMantenimiento;
    private javax.swing.JMenuItem jMenuItemEliminarProductos;
    private javax.swing.JMenuItem jMenuItemModificarClientes;
    private javax.swing.JMenuItem jMenuItemModificarMantenimiento;
    private javax.swing.JMenuItem jMenuItemModificarProductos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
